 # Main language/toolchain
language: csharp

# Mono is not required for this project
mono: none

# Install .NET Core (LTS)
dotnet: 1.0.4

# Operating systems to test against
os: linux

# Disable sudo to enable running inside a container
sudo: false

# Global environment variables
env:
- BUILD_CONFIG="Debug" DOTNET_CLI_TELEMETRY_OPTOUT=1
- BUILD_CONFIG="Release" DOTNET_CLI_TELEMETRY_OPTOUT=1

## NOTE: See the following url for the versions of the .NET Core SDK, runtime etc.
##       https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview2-download.md

# Install dependencies
install:
  - bash <(curl -s https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh) --channel "LTS" --version "latest"
  - bash <(curl -s https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh) --channel "2.0" --version "2.0.0-preview2-006497"
  - bash <(curl -s https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh) --channel "2.0" --version "latest"

# Setup for the build script
before_script:
  - export PATH=$HOME/.dotnet:$PATH

# Build script
script:
  - dotnet restore
  - dotnet build --configuration ${BUILD_CONFIG}
  - dotnet test --configuration ${BUILD_CONFIG} --no-build UnitTests
  - dotnet pack --configuration ${BUILD_CONFIG} --no-build

# Additional jobs that run after tests
jobs:
  include:

    - stage: myget.org
      script: skip
      env: BUILD_CONFIG="Release" DOTNET_CLI_TELEMETRY_OPTOUT=1
      os: linux
      deploy:
        provider: script
        script: .scripts/deploy.sh $BUILD_CONFIG $MYGET_API_KEY https://www.myget.org/F/didstopia-prerelease/api/v2
        skip_cleanup: true
        on:
          repo: Didstopia/FeatherJSON
          branch: master
          tags: false
    
    - stage: nuget.org
      script: skip
      env: BUILD_CONFIG="Release" DOTNET_CLI_TELEMETRY_OPTOUT=1
      os: linux
      deploy:
        provider: script
        script: .scripts/deploy.sh $BUILD_CONFIG $NUGET_API_KEY
        skip_cleanup: true
        on:
          repo: Didstopia/FeatherJSON
          branch: master
          tags: true

    - stage: GitHub Release
      script:
        - dotnet restore
        - dotnet build -c $BUILD_CONFIG
        - dotnet pack -c $BUILD_CONFIG --no-build
      env: BUILD_CONFIG="Release" DOTNET_CLI_TELEMETRY_OPTOUT=1
      os: linux
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file:
          - "Didstopia.FeatherJSON/bin/${BUILD_CONFIG}/*.nupkg"
          - "Didstopia.FeatherJSON.Extensions/bin/${BUILD_CONFIG}/*.nupkg"
        skip_cleanup: true
        on:
          repo: Didstopia/FeatherJSON
          branch: master
          tags: true

cache:
  directories:
    - $HOME/.nuget/packages
    - $HOME/.dotnet/NuGetFallbackFolder
